In [77]:
import numpy as np
import pandas as pd

## Creating Array

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#crete a 3/4 array with zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# It will create a evenly divided elements 
# create a 6 elements from 0 to 100

np.linspace(0,101,6)

array([  0. ,  20.2,  40.4,  60.6,  80.8, 101. ])

In [26]:
# create a random element with 4/5 array
# random.rand will always create a float value
np.random.rand(4,5)

array([[0.3080365 , 0.54293999, 0.92192405, 0.33446171, 0.47125041],
       [0.76811523, 0.14665816, 0.41099148, 0.33235623, 0.23547991],
       [0.84483176, 0.93973335, 0.82058336, 0.169245  , 0.78929015],
       [0.30255328, 0.4296091 , 0.04656009, 0.57723143, 0.83492546]])

In [30]:
# 2x3 array with random ints between 0–6
# random.randint will always create a int value
np.random.randint(6,size=(2,3))         

array([[0, 0, 1],
       [0, 0, 5]])

## Concating array 

In [53]:
arr3=np.random.randint(5,size=(2,3))
arr3

arr4=np.random.randint(20,size=(2,3))
arr3

array([[2, 1, 1],
       [0, 0, 4]])

In [56]:
# Adds arr2 as columns to end of arr1

concat_by_col=np.concatenate((arr3,arr4),axis=1)
concat_by_col


array([[ 2,  1,  1,  7, 16,  4],
       [ 0,  0,  4,  2,  6,  9]])

In [59]:
# Adds arr2 as rows to the end of arr1
concat_by_row=np.concatenate((arr3,arr4),axis=0)
concat_by_row

array([[ 2,  1,  1],
       [ 0,  0,  4],
       [ 7, 16,  4],
       [ 2,  6,  9]])

## Vector Math

In [63]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr2 = np.array([[7, 6, 8], [9, 10, 11]])
arr2

array([[ 7,  6,  8],
       [ 9, 10, 11]])

In [67]:
# Adding two array arr1 and arr2

sum_of_array=np.add(arr1,arr2)
sum_of_array


array([[ 8,  8, 11],
       [13, 15, 17]])

In [ ]:
# np.subtract(arr1,arr2)
# np.multiply(arr1,arr2)
# np.divide(arr1,arr2)
# np.log(arr)    Natural log of each element in the array
# np.sqrt(arr)   Square root of each element in the array
# np.round(arr)  Rounds to the nearest int
# np.floor(arr)  np.floor(arr)

In [68]:
# Returns sum of arr
arr1.sum()

21

In [69]:
# Returns the variance of array
np.var(arr1)

2.9166666666666665

In [72]:
# Returns correlation coefficient of array
np.corrcoef(arr1)

array([[1., 1.],
       [1., 1.]])

In [74]:
# Returns the standard deviation of specific axis
np.std(arr,axis=1)


array([0.81649658, 0.81649658])

In [75]:
# Raise each array element to the 5th power
np.power(arr1,5)

array([[   1,   32,  243],
       [1024, 3125, 7776]], dtype=int32)

In [76]:
# Multiply each array element by 3
np.multiply(arr1,3)

array([[ 3,  6,  9],
       [12, 15, 18]])